title: Building Software Together
subtitle: "a student's guide to being a compassionate programmer"
url: https://buildtogether.tech
repository: gvwilson/buildtogether.tech
default_image: /static/fixme.svg
cover_image: /static/bst-600.jpg

chapters:
  - slug: "introduction"
    title: "Introduction"
  - slug: "important"
    title: "The Important Stuff"
  - slug: "starting"
    title: "Starting"
  - slug: "teams"
    title: "Teams"
  - slug: "rules-persuade"
    title: "How to Talk People Into Things"
  - slug: "conflict"
    title: "Managing Conflict"
  - slug: "git-solo"
    title: "Using Git On Your Own"
  - slug: "git-team"
    title: "Using Git Together"
  - slug: "ip"
    title: "Intellectual Property"
  - slug: "communicate"
    title: "Communicating"
  - slug: "testing"
    title: "Testing"
  - slug: "design"
    title: "Software Design"
  - slug: "security"
    title: "Security"
  - slug: "errors"
    title: "Error Handling"
  - slug: "debugging"
    title: "Debugging"
  - slug: "automation"
    title: "Automation"
  - slug: "tooling"
    title: "Tooling"
  - slug: "rules-comfortable"
    title: "How to Make Yourself Comfortable"
  - slug: "process"
    title: "Process"
  - slug: "rules-newcomers"
    title: "How to Welcome Newcomers"
  - slug: "research"
    title: "Research"
  - slug: "rules-research"
    title: "How to be a Good Research Partner"
  - slug: "fairness"
    title: "Fair Play"
  - slug: "rules-joining"
    title: "How to Join an Existing Project"
  - slug: "rules-fired"
    title: "How to Handle Being Fired"
  - slug: "delivery"
    title: "Wrapping Up"
  - slug: "rules-handover"
    title: "How to Hand Over and Move On"
  - slug: "conclusion"
    title: "Conclusion"
  - appendix: true
  - slug: "license"
    title: "License"
    file: "LICENSE.md"
  - slug: "bibliography"
    title: "Bibliography"
  - slug: "conduct"
    title: "Code of Conduct"
    file: "CODE_OF_CONDUCT.md"
  - slug: "contributing"
    title: "Contributing"
    file: "CONTRIBUTING.md"
  - slug: "glossary"
    title: "Glossary"
  - slug: "links"
    title: "Links"
  - slug: "thinking"
    title: "Thinking and Learning"
  - slug: "methods"
    title: "Research Methods"
  - slug: "onboarding"
    title: "Onboarding Checklist"
  - slug: "project-eval"
    title: "Project Evaluation"
  - slug: "personal-eval"
    title: "Personal Evaluation"
  - slug: "reading"
    title: "Further Reading"
  - slug: "rules-freelance"
    title: "How to Get Started Freelancing"
  - slug: "rules-change"
    title: "How to Change the World"
  - slug: "authors"
    title: "Authors"
  - slug: "index"
    title: "Index"
    skip: true

author:
  name: Greg Wilson
  url: third-bit.com
  email: gvwilson@third-bit.com
  github: https://github.com/gvwilson
  twitter: https://twitter.com/gvwilson
  linkedin: https://www.linkedin.com/in/greg-wilson-a26510b6/

markdown: kramdown

kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter_opts:
    disable: true
  link_defs: >
    {
      "adhd-thread": ["https://twitter.com/NomeDaBarbarian/status/1369846245200515072", "A thread on ADHD"],
      "alloy": ["https://alloytools.org/", "Alloy"],
      "ant": ["https://ant.apache.org/", "Apache Ant"],
      "aosa": ["https://aosabook.org/", "The Architecture of Open Source Applications"],
      "apache": ["https://apache.org/", "Apache Software Foundation"],
      "apt": ["https://en.wikipedia.org/wiki/APT_(software)", "APT"],
      "ask-a-manager": ["https://www.askamanager.org/", "Ask a Manager"],
      "atlassian-git": ["https://www.atlassian.com/git/tutorials", "Atlassian Git tutorials"],
      "automattic-hiring": ["https://automattic.com/work-with-us/how-we-hire-developers/", "Automattic hiring process"],
      "baxter-interviews": ["https://github.com/tBaxter/questions-for-employers", "Questions for potential employers"],
      "baxter-t-carter": ["https://twitter.com/tbaxter", "T. Carter Baxter"],
      "bitbucket": ["https://bitbucket.org/", "Bitbucket"],
      "black": ["https://pypi.org/project/black/", "Black"],
      "blackbox": ["https://bluej.org/blackbox/", "Blackbox"],
      "bleachbit": ["https://www.bleachbit.org/", "BleachBit"],
      "block-party": ["https://www.blockpartyapp.com/", "Block Party"],
      "brown-neil": ["https://twistedsquare.com/", "Neil C. C. Brown"],
      "bst-repo": ["https://github.com/gvwilson/buildtogether.tech/", "Building Software Together repository"],
      "burns-privacy-quote": ["https://webdevlaw.uk/2021/03/21/privacy-curriculum-developers/", "Heather Burns on privacy"],
      "buzzfeed-datacamp": ["http://third-bit.com/2019/04/22/datacamp-clarifications/", "DataCamp Clarifications"],
      "captain-awkward": ["https://www.buzzfeednews.com/article/daveyalba/datacamp-sexual-harassment-metoo-tech-startup ", "Buzzfeed article on DataCamp"],
      "carnac": ["http://code52.org/carnac/", "Carnac"],
      "carpentries": ["https://carpentries.org/", "The Carpentries"],
      "carpentries-git": ["https://swcarpentry.github.io/git-novice/", "The Carpentries' lesson on Git"],
      "carpentrycon-talk": ["https://www.youtube.com/watch?v=7xR50ty5DZ0", "Greg Wilson's CarpentryCon keynote"],
      "charles-rules": ["https://geekfeminism.wikia.com/wiki/Charles%27_Rules_of_Argument", "Charles' Rules of Argument"],
      "checkstyle": ["https://checkstyle.org/", "Checkstyle"],
      "choose-license": ["https://choosealicense.com/", "Choose a License"],
      "coco": ["https://coco-net.org/", "Centre for Community Organizations"],
      "coco-problem": ["https://coco-net.org/problem-woman-colour-nonprofit-organizations/", "The 'Problem' Woman of Colour in the Workplace"],
      "contributor-covenant": ["https://www.contributor-covenant.org", "Contributor Covenant"],
      "conways-law": ["https://en.wikipedia.org/wiki/Conway%27s_law", "Conway's Law"],
      "cook-mary-rose": ["https://maryrosecook.com/", "Mary Rose Cook"],
      "creative-commons": ["https://creativecommons.org/", "Creative Commons"],
      "ctan": ["https://www.ctan.org/", "The Comprehensive TeX Archive Network"],
      "curley-april": ["https://twitter.com/RealAbril", "April Christina Curley"],
      "cvs": ["https://www.nongnu.org/cvs/", "CVS"],
      "diagrams": ["https://www.diagrams.net/", "diagrams.net drawing tool"],
      "diffmerge": ["https://sourcegear.com/diffmerge/", "SourceGear DiffMerge"],
      "dlf": ["https://www.diglib.org/", "Digital Library Foundation"],
      "dlf-active-bystander": ["https://www.diglib.org/active-bystander-orientation/", "DLF Active Bystander Orientation"],
      "dobzhansky": ["https://en.wikipedia.org/wiki/Nothing_in_Biology_Makes_Sense_Except_in_the_Light_of_Evolution", "Nothing in biology makes sense except in the light of evolution"],
      "docker": ["https://www.docker.com/", "Docker"],
      "doi2bib": ["https://doi2bib.org/", "Turn DOIs into bibliography entries"],
      "dropbox": ["https://dropbox.com", "Dropbox"],
      "duckduckgo": ["https://duckduckgo.com/", "DuckDuckGo"],
      "eiffel": ["https://www.eiffel.org/", "Eiffel"],
      "emacs": ["https://www.gnu.org/software/emacs/", "Emacs"],
      "email": ["mailto:gvwilson@third-bit.com", "Contact address"],
      "evans-julia": ["https://jvns.ca/", "Julia Evans"],
      "evans-interviews": ["https://jvns.ca/blog/2013/12/30/questions-im-asking-in-interviews/", "Questions I'm Asking in Interviews"],
      "evans-manager": ["https://jvns.ca/blog/things-your-manager-might-not-know/", "Things Your Manager Might Not Know"],
      "eslint": ["https://eslint.org/", "ESLint"],
      "excel-tweet": ["https://twitter.com/gvwilson/status/776733301419630592", "Tweet about Excel and evidence"],
      "facebook-rohingya": ["https://www.buzzfeednews.com/article/meghara/facebook-myanmar-rohingya-genocide", "How Facebook Failed the Rohingya in Myanmar"],
      "fileshredder": ["https://voidtech.net/apps/fileshredder/", "FileShredder"],
      "flower-annalee": ["https://flowerhorne.com/", "Annalee Flower"],
      "flower-good-intent": ["https://thebias.com/2017/09/26/how-good-intent-undermines-diversity-and-inclusion/", "How 'Good Intent' Undermines Diversity and Inclusion"],
      "gdb": ["https://www.gnu.org/software/gdb/", "GDB"],
      "gdpr": ["https://en.wikipedia.org/wiki/General_Data_Protection_Regulation", "General Data Protection Regulation"],
      "gdpr-forgotten": ["https://www.gdpreu.org/right-to-be-forgotten/", "GDPR-mandated right to be forgotten"],
      "gebru-firing": ["https://www.fastcompany.com/90608471/timnit-gebru-google-ai-ethics-equitable-tech-movement", "This is bigger than just Timnit"],
      "gender-decoder": ["http://gender-decoder.katmatfield.com/", "Gender Decoder"],
      "gendermag": ["http://gendermag.org/", "GenderMag"],
      "ghostery": ["https://www.ghostery.com/", "Ghostery"],
      "git": ["https://git-scm.com/", "Git"],
      "git-difftool": ["https://git-scm.com/docs/git-difftool", "git difftool"],
      "git-man-page-generator": ["https://git-man-page-generator.lokaltog.net/", "Git Random Man Page Generator"],
      "github": ["https://github.com/", "GitHub"],
      "github-actions": ["https://github.com/features/actions", "GitHub Actions"],
      "github-guides": ["https://guides.github.com/", "GitHub Guides"],
      "github-pages": ["https://pages.github.com/", "GitHub Pages"],
      "gitkraken": ["https://www.gitkraken.com/", "GitKraken"],
      "gitlab": ["https://gitlab.com/", "GitLab"],
      "gitlet": ["http://gitlet.maryrosecook.com/", "Gitlet"],
      "goodhart-law": ["https://en.wikipedia.org/wiki/Goodhart%27s_law", "Goodhart's Law"],
      "grand-perspective": ["http://grandperspectiv.sourceforge.net/", "Grand Perspective"],
      "gritter-alloy": ["https://medium.com%2F@medium.com/@markgritter/finding-graph-counterexamples-with-alloy-e4114cc0f2fb", "Finding Graph Counterexamples with Alloy"],
      "gritter-tla-plus": ["https://medium.com%2F@medium.com/@fuzz_ai/reproducing-a-memory-tracking-bug-with-tla-35ce0652ce72", "Reproducing a Memory-Tracking Bug with TLA+"],
      "hanselman-dark-matter": ["https://www.hanselman.com/blog/dark-matter-developers-the-unseen-99", "Dark Matter Developers: The Unseen 99%"],
      "hanselman-scott": ["https://www.hanselman.com/", "Scott Hanselman"],
      "hippocratic-license": ["https://firstdonoharm.dev/", "Hippocratic License"],
      "homebrew": ["https://en.wikipedia.org/wiki/Homebrew_(package_manager)", "Homebrew"],
      "hoye-mike": ["http://exple.tive.org/", "Mike Hoye"],
      "jekyll": ["https://jekyllrb.com/", "Jekyll"],
      "jekyll-bug": ["https://stackoverflow.com/questions/66320774/how-to-pre-define-links-in-jekyll-config-yml-using-kramdown-links-def-options", "A bug in Jekyll"],
      "jira": ["https://www.atlassian.com/software/jira", "Jira"],
      "js4ds": ["https://js4ds.org/", "JavaScript for Data Science"],
      "jsdoc": ["https://jsdoc.app/", "JSDoc"],
      "kaplan-moss-executives": ["https://jacobian.org/2021/mar/5/exec-status-update/", "How to Give a Status Update to Executives"],
      "kaplan-moss-jacob": ["https://jacobian.org/", "Jacob Kaplan-Moss"],
      "lua": ["https://www.lua.org/", "Lua"],
      "make": ["https://www.gnu.org/software/make/", "GNU Make"],
      "marthas-rules": ["https://journals.sagepub.com/doi/10.1177/088610998600100206", "Martha's Rules"],
      "mathml": ["https://www.w3.org/Math/", "MathML"],
      "mercurial": ["https://www.mercurial-scm.org/", "Mercurial"],
      "namely-time-off": ["https://library.namely.com/hr-mythbusters-2017", "2017 HR Mythbusters report"],
      "noaa-disruptive": ["https://coast.noaa.gov/ddb/", "Dealing with Disruptive Behaviors"],
      "nodejs": ["https://nodejs.org/en/", "Node.js"],
      "npm": ["https://en.wikipedia.org/wiki/Npm_(software)", "NPM"],
      "npm-xml-search": ["https://www.npmjs.com/search?q=xml%20parser", "XML parsers on NPM"],
      "npms": ["https://npms.io/about", "About NPMS scores"],
      "osi": ["https://opensource.org/", "Open Source Initiative"],
      "osi-license-list": ["https://opensource.org/licenses", "Open Source Initiative License List"],
      "paradox-of-tolerance": ["https://en.wikipedia.org/wiki/Paradox_of_tolerance", "Paradox of tolerance"],
      "pep8": ["https://www.python.org/dev/peps/pep-0008/", "PEP 8 Style Guide for Python Code"],
      "petre-marian": ["https://www.open.ac.uk/people/mp8", "Marian Petre"],
      "petrov-handing-over": ["https://shazow.net/posts/how-to-hand-over-an-open-source-project-to-a-new-maintainer/", "How to hand over an Open Source project to a new maintainer"],
      "pip": ["https://pypi.org/project/pip/", "pip"],
      "plantuml": ["https://plantuml.com/", "PlantUML"],
      "plos": ["https://plos.org/", "PLOS"],
      "privacy-right": ["https://en.wikipedia.org/wiki/Right_to_privacy", "Right to privacy"],
      "program-repair": ["https://program-repair.org/", "Program Repair"],
      "pryce-nat": ["http://www.natpryce.com/", "Nat Pryce"],
      "pryce-onboarding": ["https://twitter.com/natpryce/status/1375949072910200835", "Onboarding checklist"],
      "python": ["https://www.python.org/", "Python"],
      "pytest": ["http://pytest.org/", "pytest"],
      "pytest-benchmark": ["https://pypi.org/project/pytest-benchmark/", "pytest-benchmark"],
      "quarterback-syndrome": ["https://en.wikipedia.org/wiki/Racial_issues_faced_by_black_quarterbacks", "Quarterback syndrome"],
      "quorum": ["https://quorumlanguage.com/", "Quorum"],
      "rake": ["https://ruby.github.io/rake/", "Rake"],
      "red-door": ["https://www.reddoorshelter.ca/", "Red Door Family Shelter"],
      "ruby": ["https://www.ruby-lang.org/", "Ruby"],
      "schneier-bruce": ["https://www.schneier.com/", "Bruce Schneier"],
      "sci-hub": ["https://en.wikipedia.org/wiki/Sci-Hub", "Sci-Hub"],
      "scratch": ["https://scratch.mit.edu/", "Scratch"],
      "selenium": ["https://www.selenium.dev/", "Selenium"],
      "smartbear-code-review": ["https://smartbear.com/learn/code-review/best-practices-for-peer-code-review/", "Best Practices for Peer Code Review"],
      "snakemake": ["https://snakemake.readthedocs.io/en/stable/", "Snakemake"],
      "so-configure-git-editor": ["https://stackoverflow.com/questions/2596805/how-do-i-make-git-use-the-editor-of-my-choice-for-commits", "How do I make Git use the editor of my choice for commits?"],
      "so-exit-vim": ["https://stackoverflow.com/questions/11828270/how-do-i-exit-the-vim-editor", "How do I exit the Vim editor?"],
      "sourcetree": ["https://www.sourcetreeapp.com/", "SourceTree"],
      "sqlite": ["https://www.sqlite.org/", "SQLite"],
      "stack-overflow": ["https://stackoverflow.com/", "Stack Overflow"],
      "stack-overflow-good-question": ["https://stackoverflow.com/help/how-to-ask", "How do I ask a good question?"],
      "stjs": ["https://stjs.tech/", "Software Tools in JavaScript"],
      "subversion": ["https://subversion.apache.org/", "Subversion"],
      "t3": ["http://teachtogether.tech/", "Teaching Tech Together"],
      "t3-personas": ["https://teachtogether.tech/en/index.html#s:process-personas", "Learner Personas"],
      "taylor-francis": ["https://taylorandfrancis.com/", "Taylor & Francis"],
      "tech-solidarity": ["https://techsolidarity.org/", "Tech Solidarity"],
      "therac-25": ["https://en.wikipedia.org/wiki/Therac-25", "Therac-25"],
      "thirdbit-burnout": ["http://third-bit.com/2015/11/09/daddy-why-dont-you-ever-laugh/", "Daddy, Why Don't You Ever Laugh?"],
      "tla-plus": ["https://lamport.azurewebsites.net/tla/tla.html", "TLA+"],
      "tldr-gpl": ["https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)", "tl;dr summary of the GPL"],
      "tldr-legal": ["https://tldrlegal.com/", "Software Licenses in Plain English"],
      "travis-ci": ["https://travis-ci.org/", "Travis CI"],
      "udhr": ["https://en.wikipedia.org/wiki/Universal_Declaration_of_Human_Rights", "Universal Declaration of Human Rights"],
      "uk-home-office-a11y": ["https://ukhomeoffice.github.io/accessibility-posters/posters/accessibility-posters.pdf", "UK Home Office posters on accessibility"],
      "ultima-online-players": ["https://twitter.com/ZenOfDesign/status/1371347166736834560", "Number of badly-behaved players in Ultima Online"],
      "visual-basic": ["https://en.wikipedia.org/wiki/Visual_Basic", "Visual Basic"],
      "vs-code": ["https://code.visualstudio.com/", "Microsoft Visual Studio Code"],
      "wapost-facebook-vaccine": ["https://www.washingtonpost.com/technology/2021/03/14/facebook-vaccine-hesistancy-qanon/", "Massive Facebook study on users' doubt in vaccines finds a small group appears to play a big role in pushing the skepticism"],
      "wayne-hillel": ["https://hillelwayne.com/", "Hillel Wayne"],
      "wayne-linked-lists": ["https://www.hillelwayne.com/post/linked-lists/", "Why Do Interviewers Ask Linked List Questions?"],
      "webaim-wave": ["https://wave.webaim.org/", "WebAIM WAVE"],
      "wilson-greg": ["https://third-bit.com/", "Greg Wilson"],
      "womens-work": ["https://en.wikipedia.org/wiki/Women%27s_work", "Women's work"],
      "xkcd-passwords": ["https://xkcd.com/936/", "XKCD on secure passwords"]
    }

exclude:
  - '*.sublime-*'
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - book.*
  - tmp

permalink: pretty
